version: '3.9'

services:
  postgres:
    container_name: nolabel_db
    image: postgres:15
    restart: always
    env_file: ./backend/.env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - net

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: nolabel_backend
    ports:
      - '8000:8000'
    networks:
      - net
    restart: always

volumes:
  postgres-data:
  minio_data:

networks:
  net:
