FROM python:3.12-slim
WORKDIR .
RUN apt update

COPY ./requirements.txt ./

RUN pip install -r requirements.txt

EXPOSE 8000

COPY . .

CMD alembic upgrade head && uvicorn app:app --host 0.0.0.0 --port 8000