version: '3'

services:
  postgres:
    container_name: nolabel_db
    image: postgres:15
    restart: always
    env_file: ./.env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - net

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: nolabel_backend
    ports:
      - '8000:8000'
    networks:
      - net
    restart: always
    depends_on:
      - postgres

  node1:
    build:
      context: .
      dockerfile: Dockerfile.blockchain
    container_name: blockchain_node1
    ports:
      - "5001:5000"
    environment:
      - PORT=5000
      - NODE_NAME=node1
      - KNOWN_NODES=node2:5000,node3:5000
    networks:
      - net
    restart: always

  node2:
    build:
      context: .
      dockerfile: Dockerfile.blockchain
    container_name: blockchain_node2
    ports:
      - "5002:5000"
    environment:
      - PORT=5000
      - NODE_NAME=node2
      - KNOWN_NODES=node1:5000,node3:5000
    networks:
      - net
    restart: always

  node3:
    build:
      context: .
      dockerfile: Dockerfile.blockchain
    container_name: blockchain_node3
    ports:
      - "5003:5000"
    environment:
      - PORT=5000
      - NODE_NAME=node3
      - KNOWN_NODES=node1:5000,node2:5000
    networks:
      - net
    restart: always

volumes:
  postgres-data:
  minio_data:

networks:
  net:
