"""ACL migration - refactor ACL concept

Revision ID: 2c1a718cb706
Revises: 98ba6e88840d
Create Date: 2025-02-02 20:06:56.423471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c1a718cb706'
down_revision: Union[str, None] = '98ba6e88840d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_role',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('role_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('role', sa.Column('resource_id', sa.UUID(), nullable=True))
    op.alter_column('role', 'name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.add_column('role_permission', sa.Column('is_allowed', sa.Boolean(), nullable=True))
    op.alter_column('user', 'first_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('user', 'last_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_constraint('user_role_id_fkey', 'user', type_='foreignkey')
    op.drop_column('user', 'role_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('role_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('user_role_id_fkey', 'user', 'role', ['role_id'], ['id'], ondelete='CASCADE')
    op.alter_column('user', 'last_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('user', 'first_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.drop_column('role_permission', 'is_allowed')
    op.alter_column('role', 'name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.drop_column('role', 'resource_id')
    op.drop_table('user_role')
    # ### end Alembic commands ###
